const questions = [
    {
        q: "👴",
        ans1: "Grandmother",
        ans2: "Grandfather ",
        true: "option2",
      },
      {
        q: "😁",
        ans1: "Sad",
        ans2: "Happy",
        true: "option2",  
    },
    {
        q: "Snake",
        ans1: "🐍",
        ans2: "🐊",
        true: "option1",
      },
      {
        q: "❄️+👱‍♂️",
        ans1: "Snowman",
        ans2: "Snow",
        true: "option1",  
    },{
        q: "👓+🌞",
        ans1: "Snowman",
        ans2: "Sunglasses ",
        true: "option2",
      },
      {
        q: "up",
        ans1: "⬇️",
        ans2: "⬆️",
        true: "option2",
    },
    {
        q: "🧠",
        ans1: "Brain",
        ans2: "Pink",
        true: "option1",
      },
      {
        q: "Teacher",
        ans1: " 📝",
        ans2: "👩🏼‍🏫",
        true: "option2",  
    },
    {
        q: "yellow",
        ans1: " 🍋 ",
        ans2: " 🟨 ",
        true: "option2",
      },
      {
        q: "Zebra",
        ans1: "🐄",
        ans2: "🦓 ",
        true: "option2",  
    },
    {
        q: "📷",
        ans1: "Lamp",
        ans2: "Camera",
        true: "option2",
      },
      {
        q: "Grandmother",
        ans1: " 👨 ",
        ans2: "👵",
        true: "option2",  
    },
    {
        q: "Mouse",
        ans1: " 🐇 ",
        ans2: "🐁",
        true: "option2",
      },
      {
        q: "Pop+ 🌽 ",
        ans1: "🍟",
        ans2: " 🍿",
        true: "option2",  
    },
    {
        q: "Sky color",
        ans1: "🟦",
        ans2: "🟫",
        true: "option1",
      },
      {
        q: "Umbrella",
        ans1: "🧥",
        ans2: " ☂️ ",
        true: "option2",  
    },
    {
        q: "Spaceship",
        ans1: "🛸",
        ans2: "🚤",
        true: "option1",
      },
      {
        q: "🍒 🍑 🥭 🥥 🥝",
        ans1: "Vegetables",
        ans2: "Fruits",
        true: "option2",  
    },
    {
        q: "🎲",
        ans1: "Cube",
        ans2: "Game",
        true: "option1",
      },
      {
        q: "✈️",
        ans1: "Rain",
        ans2: "Plane ",
        true: "option2",  
    },
    {
        q: "🟥+🟦=",
        ans1: "Green",
        ans2: "Purple",
        true: "option2",
      },
      {
        q: "🎧",
        ans1: "Headphones",
        ans2: "Earrings",
        true: "option1",  
    },
    {
        q: "one + one",
        ans1: "2",
        ans2: "11",
        true: "option1",  
    },
    {
        q: "🐶",
        ans1: "Dog",
        ans2: "Hotdog",
        true: "option1",  
    },
    {
        q: "✏️",
        ans1: "Pen",
        ans2: "Pencil",
        true: "option2",  
    },
    {
        q: "📖",
        ans1: "Book",
        ans2: "Notebook",
        true: "option1",  
    },
    {
        q: "✨",
        ans1: "Stars",
        ans2: "Wishes",
        true: "option1",  
    },
    {
        q: "😴",
        ans1: "Sleep",
        ans2: "Awake",
        true: "option1",  
    },
    {
        q: "Music",
        ans1: "🎶🎵",
        ans2: "🎧",
        true: "option1",  
    },
    {
        q: "💻",
        ans1: "Computer",
        ans2: "Laptop",
        true: "option2",  
    },
    {
        q: "💊",
        ans1: "Medicine",
        ans2: "Candy",
        true: "option1",  
    },
    {
        q: "🍭",
        ans1: "Lolipop",
        ans2: "Stick",
        true: "option1",  
    },
    {
        q: "🪄",
        ans1: "Magic hat",
        ans2: "Magic wand",
        true: "option2",  
    },
    {
        q: "❤️",
        ans1: "Heart",
        ans2: "Hurt",
        true: "option1",  
    },
    {
        q: "🚗",
        ans1: "Car",
        ans2: "Cart",
        true: "option1",  
    },
    {
        q: "🪟",
        ans1: "Glass",
        ans2: "Window",
        true: "option2",  
    },
    {
        q: "💽",
        ans1: "Desk",
        ans2: "Disk",
        true: "option2",  
    },
    {
        q: "Doctor",
        ans1: "🧑‍⚕️",
        ans2: "💉",
        true: "option1",  
    },
    {
        q: "Carrot",
        ans1: "🥕",
        ans2: "🐰",
        true: "option1",  
    },
    {
        q: "Ear",
        ans1: "🎧",
        ans2: "👂",
        true: "option2",  
    },
    {
        q: "👻",
        ans1: "Ghost",
        ans2: "Boo!",
        true: "option1",  
    },
    {
        q: "Lamp",
        ans1: "🛋️",
        ans2: "🦒",
        true: "option1",  
    },
    {
        q: "Shirt",
        ans1: "👖",
        ans2: "👕",
        true: "option2",  
    },
    {
        q: "Cup",
        ans1: "🥤",
        ans2: "⛑️",
        true: "option1",  
    },
    {
        q: "Banana",
        ans1: "🍌",
        ans2: "🐒",
        true: "option1",  
    },
    {
        q: "Monkey",
        ans1: "🍌",
        ans2: "🐒",
        true: "option2",  
    },
    {
        q: "Earth",
        ans1: "🌙",
        ans2: "🌍",
        true: "option2",  
    },
];