const questions = [
    {
        q: "נאטיכוסי",
        ans1: "אנטיוכוס",
        ans2: "אטניוכוס",
        true: "option1",
      },
      {
        q: "טבהט",
        ans1: "בטטה",
        ans2: "בטהטה",
        true: "option1",
      },
      {
        q: "בננה",
        ans1: "בהננ",
        ans2: "בננה",
        true: "option2",
      },
      {
        q: "יהיקאנופצלד",
        ans1: "אנציקלופדיה",
        ans2: "אנצילקופדיה",
        true: "option1",
      },
      {
        q: "פלקורןקס",
        ans1: "קונרפלקס",
        ans2: "קורנפלקס",
        true: "option2",
      },
      {
        q: "יחאבט",
        ans1: "אבטיח",
        ans2: "אבחיט",
        true: "option1",
      },
      {
        q: "ונואוטמיה",
        ans1: "אוטונומיה",
        ans2: "אנטומוניה",
        true: "option1",
      },
      {
        q: "מאיתש",
        ans1: "מאשית",
        ans2: "משאית",
        true: "option2",
      },
      {
        q: "חןשול",
        ans1: "שולחן",
        ans2: "חולשן",
        true: "option1",
      },
      {
        q: "בומש",
        ans1: "בושם",
        ans2: "בוסם",
        true: "option1",
      },
      {
        q: "ננערה",
        ans1: "רעננה",
        ans2: "נערה",
        true: "option1",
      },
      {
        q: "פחת קוותה",
        ans1: "פתח תקווה",
        ans2: "פחית מקווה",
        true: "option1",
      },
      {
        q: "טלש",
        ans1: "סלט",
        ans2: "שלט",
        true: "option2",
      },
      {
        q: "תפרוה",
        ans1: "תרופה",
        ans2: "פרווה",
        true: "option1",
      },
      {
        q: "ופורה",
        ans1: "פורה",
        ans2: "פרווה",
        true: "option2",
      },
      {
        q: "פערה",
        ans1: "עפרה",
        ans2: "פרעה",
        true: "option2",
      },
      {
        q: "תתמרש",
        ans1: "מתרשת",
        ans2: "משרתת",
        true: "option2",
      },
      {
        q: "תמרשת",
        ans1: "משרתת",
        ans2: "תמשורת",
        true: "option1",
      },
      {
        q: "מתרוס",
        ans1: "תמרוס",
        ans2: "תרמוס",
        true: "option2",
      },
      {
        q: "נועש",
        ans1: "שעון",
        ans2: "עשון",
        true: "option1",
      },
      {
        q: "כהשב",
        ans1: "כביסה",
        ans2: "כבשה",
        true: "option2",
      },
      {
        q: "נבלו",
        ans1: "בלון",
        ans2: "נבל",
        true: "option1",
      },
      {
        q: "דורכ",
        ans1: "כדור",
        ans2: "דרוך",
        true: "option1",
      },
      {
        q: "טרטיס",
        ans1: "טטריס",
        ans2: "סיטרס",
        true: "option1",
      },
      {
        q: "םירשי",
        ans1: "שרים",
        ans2: "שירים",
        true: "option2",
      },
      {
        q: "משבח",
        ans1: "מכשב",
        ans2: "מחשב",
        true: "option2",
      },
      {
        q: "מתרוס",
        ans1: "תמרוס",
        ans2: "תרמוס",
        true: "option1",
      },
      {
        q: "מרטה",
        ans1: "מטרה",
        ans2: "תמרה",
        true: "option1",
      },
      {
        q: "חקול",
        ans1: "חלוק",
        ans2: "מחלוקת",
        true: "option2",
      },
      {
        q: "קרלמ",
        ans1: "כרמל",
        ans2: "קלמר",
        true: "option2",
      },
      {
        q: "חולת",
        ans1: "חיתול",
        ans2: "חתול",
        true: "option2",
      },
      {
        q: "גירטה",
        ans1: "גיטרה",
        ans2: "גירטה",
        true: "option1",
      },
      {
        q: "וניול",
        ans1: "וניל",
        ans2: "וילון",
        true: "option2",
      },
      {
        q: "בקבקו",
        ans1: "בקבק",
        ans2: "בקבוק",
        true: "option2",
      },
      {
        q: "רביעו",
        ans1: "ריבוע",
        ans2: "רבוע",
        true: "option1",
      },
      {
        q: "לינמו",
        ans1: "לינומ",
        ans2: "לימון",
        true: "option2",
      },
      {
        q: "ערתיב",
        ans1: "עברית",
        ans2: "תעריב",
        true: "option1",
      },
      {
        q: "ללחית",
        ans1: "חלליות",
        ans2: "חללית",
        true: "option2",
      },
      {
        q: "תנכון",
        ans1: "תכנון",
        ans2: "תיכון",
        true: "option1",
      },
      {
        q: "חנותה",
        ans1: "חתנוה",
        ans2: "חתונה",
        true: "option2",
      },
      {
        q: "חונכה",
        ans1: "חנוכה",
        ans2: "חנוקה",
        true: "option1",
      },
      {
        q: "מקנר",
        ans1: "מקרן",
        ans2: "נמקר",
        true: "option1",
      },
      {
        q: "תונמי",
        ans1: "מוינת",
        ans2: "מונית",
        true: "option2",
      },
      {
        q: "מניוז",
        ans1: "מיונז",
        ans2: "פיוז",
        true: "option1",
      },
      {
        q: "המשק",
        ans1: "שקמה",
        ans2: "משקה",
        true: "option2",
      },
      {
        q: "ימם",
        ans1: "מים",
        ans2: "ימים",
        true: "option1",
      },
      {
        q: "שולודק",
        ans1: "שוקולד",
        ans2: "שוקלוד",
        true: "option1",
      },
      {
        q: "גרד",
        ans1: "גדר",
        ans2: "מגרד",
        true: "option1",
      },
      {
        q: "גרס",
        ans1: "סגור",
        ans2: "סגר",
        true: "option2",
      },
      {
        q: "שפמו",
        ans1: "שפם",
        ans2: "שמפו",
        true: "option2",
      },
];